### ISSUE TITLE
Manga recommendations more than often provides no results 

### ISSUE THREAD

**Issue by ishanadvance** [jobobby04/TachiyomiSY#689]
### Steps to reproduce

> Open tachiyomi sy
> Open a sample manga such as : " A novel's extra "
> Open the same manga in TachiyomiAZ
> Check recommendations in both apps

Tachiyomi Sy has fewer or null recommendations but Tachiyomi AZ has decent recommendations

### Expected behavior

All relevant recommendations should come up

### Actual behavior

Tachiyomi Sy has fewer or null recommendations

### Tachiyomi version

1.8.5

### Android version

12

### Device

ONEPLUS 9 pro 5G

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Fixed for the next build

**Comment by ishanadvance** [comment]
@jobobby04 thank you for acknowledging this. Adding one more request, the recommendations currently come with a Japanese / Korean name as a title instead of the English one. Possible to handle that as well ?

**Comment by jobobby04** [comment]
Not properly, it just displays what Anilist/MAL provides. Anilist only displays official titles and not translated variants.

**Comment by jferdous70** [comment]
I have issue. I search recommendations for Lucky Guy in Toonily but didn't find any match. So it's still not fixed.

I checked Neko for mangadex app, and it has all correct recommendations from Anilist. But on sy, it doesn't fetch them

**Comment by jobobby04** [comment]
> I have issue. I search recommendations for Lucky Guy in Toonily but didn't find any match. So it's still not fixed.
> 
> I checked Neko for mangadex app, and it has all correct recommendations from Anilist. But on sy, it doesn't fetch them

That's unrelated to this bug

**Comment by jferdous70** [comment]
the issues looked similar so i commented here instead of making a new issue
